name: Node.js Package
on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - '*'

env:
  NODE_VERSION: 18

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest version
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}
          registry-url: https://npm.pkg.github.com/
          scope: '@entrecode'

      - name: Get npm cache directory
        id: npm-cache
        run: |
          echo "::set-output name=dir::$(npm config get cache)"

      - name: Cache NPM dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.npm-cache.outputs.dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
            
      - name: Install NPM dependencies
        run: npm ci
        working-directory: ${{ github.workspace }}

      - name: Run NPM build if present
        run: npm run build --if-present
        working-directory: ${{ github.workspace }}

      - name: Run NPM test if present
        continue-on-error: true
        timeout-minutes: 1
        run: npm run test --if-present
        working-directory: ${{ github.workspace }}

      - name: Run NPM publish
        run: npm publish
        working-directory: ${{ github.workspace }}
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}